# Generated by Django 4.1.7 on 2023-05-08 21:25

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Shoes', 'Shoes'), ('Jacket', 'Jacket'), ('T-shirt', 'T-shirt')], max_length=2550)),
                ('image', models.ImageField(upload_to='test1/clothing')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=20)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('XXS(38–40)', 'XXS(38–40)'), ('XS(40–42)', 'XS(40–42)'), ('S(42-44)', 'S(42-44)'), ('M(44–46)', 'M(44–46)'), ('L(48–50)', 'L(48–50)'), ('XL(50–52)', 'XL(50–52)'), ('XXL(54–56)', 'XXL(54–56)'), ('XXXL(56–58)', 'XXXL(56–58)'), ('Нет в наличии', 'Нет в наличии')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=150)),
            ],
        ),
    ]
