# Generated by Django 4.1.7 on 2023-05-08 21:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Boots', 'Boots'), ('Sandals', 'Sandals')], max_length=2550)),
                ('image', models.ImageField(upload_to='test1/shoes')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White')], max_length=20)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('Нет в наличии', 'Нет в наличии')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=150)),
            ],
        ),
    ]
