# Generated by Django 4.1.7 on 2023-05-10 07:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Аccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sneakers', 'Sneakers'), ('Boots', 'Boots'), ('Sandals', 'Sandals')], max_length=2550)),
                ('image', models.ImageField(upload_to='test1/shoes')),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('Нет в наличии', 'Нет в наличии')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=150)),
            ],
        ),
        migrations.AlterField(
            model_name='clothing',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S(42-44)', 'S(42-44)'), ('M(44–46)', 'M(44–46)'), ('L(48–50)', 'L(48–50)'), ('XL(50–52)', 'XL(50–52)'), ('XXL(54–56)', 'XXL(54–56)'), ('XXXL(56–58)', 'XXXL(56–58)'), ('Нет в наличии', 'Нет в наличии')], max_length=200),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('Нет в наличии', 'Нет в наличии')], max_length=200),
        ),
    ]
